---
{{- range $key, $value := .Values.environments }}

{{- $_ := set $ "env" $value }} # see https://github.com/helm/helm/issues/5979#issuecomment-518231758

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{$.Chart.Name}}-config-{{.}}"
data:
  fileserver.conf: |+
    [public-{{.}}]
      path /etc/puppetlabs/code/environments/production/puppet-files/{{.}}/files/public
      allow *
    [private-{{.}}]
      path /etc/puppetlabs/code/environments/production/puppet-files/{{.}}/files/private/%H
      allow *
  puppet.conf: |+
    [master]
    vardir = /opt/puppetlabs/server/data/puppetserver
    logdir = /var/log/puppetlabs/puppetserver
    rundir = /var/run/puppetlabs/puppetserver
    pidfile = /var/run/puppetlabs/puppetserver/puppetserver.pid
    codedir = /etc/puppetlabs/code
    default_manifest = /etc/puppetlabs/code/environments/production/puppet-files/{{.}}/manifests/
    [main]
    reports=log, foreman
    ssldir = /etc/puppetlabs/ssl
    [agent]
    reporting=true
  metrics.conf: |+

{{ tpl ($.Files.Get "files/metrics.conf") $ | indent 4 }}
---
{{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Chart.Name}}-global-config"
data:
  auth.conf: |+
{{ .Files.Get "files/auth.conf" | indent 4 }} ## indention has to be like this, otherwhise parse errors
  ca.conf: |+
{{ .Files.Get "files/ca.conf" | indent 4 }}
  global.conf: |+
{{ .Files.Get "files/global.conf" | indent 4 }}
  logback.xml: |+
{{ .Files.Get "files/logback.xml" | indent 4 }}
