---
{{- range $key, $value := .Values.environments }}
{{- $_ := set $ "env" $value }} # see https://github.com/helm/helm/issues/5979#issuecomment-518231758

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{$.Chart.Name}}-config-{{.}}"
data:
  fileserver.conf: |
{{ tpl ($.Files.Get "files/fileserver.conf") $ | indent 4 }} ## indention has to be like this, otherwhise parse errors
  puppet.conf: |
{{ tpl ($.Files.Get "files/puppet.conf") $ | indent 4 }}
  metrics.conf: |
{{ tpl ($.Files.Get "files/metrics.conf") $ | indent 4 }}
---
{{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Chart.Name}}-global-config"
data:
  auth.conf: |
{{ .Files.Get "files/auth.conf" | indent 4 }}
  ca.conf: |
{{ .Files.Get "files/ca.conf" | indent 4 }}
  global.conf: |
{{ .Files.Get "files/global.conf" | indent 4 }}
  logback.xml: |
{{ .Files.Get "files/logback.xml" | indent 4 }}
  puppetserver.conf: |
{{ tpl ($.Files.Get "files/puppetserver.conf" ) $ | indent 4 }}
  web-routes.conf: |
{{ tpl ($.Files.Get "files/web-routes.conf" ) $ | indent 4 }}
  webserver.conf: |
{{ tpl ($.Files.Get "files/webserver.conf" ) $ | indent 4 }}
  thyocotic.conf: |
{{ tpl ($.Files.Get "files/thycotic.conf" ) $ | indent 4 }}
