apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Chart.Name}}-global-config"
data:
  auth.conf: |
{{ .Files.Get "files/puppetserver/conf.d/auth.conf" | indent 4 }}
  ca.conf: |
{{ .Files.Get "files/puppetserver/conf.d/ca.conf" | indent 4 }}
  puppetserver.conf: |
{{ tpl ($.Files.Get "files/puppetserver/conf.d/puppetserver.conf") $ | indent 4 }}
  web-routes.conf: |
{{ tpl ($.Files.Get "files/puppetserver/conf.d/web-routes.conf") $ | indent 4 }}
  webserver.conf: |
{{ tpl ($.Files.Get "files/puppetserver/conf.d/webserver.conf") $ | indent 4 }}
  thyocotic.conf: |
{{ tpl ($.Files.Get "files/puppet/thycotic.conf") $ | indent 4 }}
  foreman.yaml: |
{{ tpl ($.Files.Get "files/puppet/foreman.yaml") $ | indent 4 }}
  hiera.yaml: |
{{ tpl ($.Files.Get "files/puppet/hiera.yaml") $ | indent 4 }}
  ca.cfg: |
{{ tpl ($.Files.Get "files/puppetserver/services.d/ca.cfg") $ | indent 4 }}
{{ if .Values.cloud_env_enabled}}
{{- $_ := set $ "cloud" true }}
  ca-cloud.cfg: |
{{ tpl ($.Files.Get "files/puppetserver/services.d/ca.cfg") $ | indent 4 }}
{{ end }}

{{- range $key, $value := .Values.puppetserver_settings.environments }}
{{- $_ := set $ "env" $key }} # see https://github.com/helm/helm/issues/5979#issuecomment-518231758
  fileserver-{{$key}}.conf: |
{{ tpl ($.Files.Get "files/puppet/fileserver.conf") $ | indent 4 }}
# indention has to be like this, otherwhise parse errors
  puppet-{{$key}}.conf: |
{{ tpl ($.Files.Get "files/puppet/puppet.conf") $ | indent 4 }}
  metrics-{{$key}}.conf: |
{{ tpl ($.Files.Get "files/puppetserver/conf.d/metrics.conf") $ | indent 4 }}
{{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Chart.Name}}-jenkins-config"
data:
  casc.yaml: |
{{ tpl ($.Files.Get "files/jenkins/casc.yaml") $ | indent 4 }}
  config.groovy: |
{{ tpl ($.Files.Get "files/jenkins/config.groovy") $ | indent 4 }}
  yamllint.conf: |
{{ .Files.Get "files/jenkins/yamllint.conf" | indent 4 }}
