---
{{- range .Values.image_streams }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 1
  name: {{.}}
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
---
{{- end }}

{{- range .Values.environments }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 1
  name: puppetserver-code-{{.}}
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
---
{{- end }}

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rhel7
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/rhel7:latest'
      name: latest
      referencePolicy:
        type: Source
