apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: trident-persistent-storage
    volume.beta.kubernetes.io/storage-provisioner: netapp.io/trident
  creationTimestamp: null
  name: puppetserver-foreman-facts
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
