apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: trident-persistent-storage
    volume.beta.kubernetes.io/storage-provisioner: netapp.io/trident
  creationTimestamp: null
  name: thycotic-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: ci00053160-puppetserver-thycotic-cache-e7c57
status: {}
