mysql_host: {{ $.Values.autosigning_mysql_host }}
mysql_user: {{ $.Values.autosigning_mysql_user }}
mysql_passwd: {{ $.Values.autosigning_mysql_password }}
mysql_db: {{ $.Values.autosigning_mysql_database }}
mysql_port: {{ $.Values.autosigning_mysql_port }}
