apiVersion: v1
kind: List
metadata:
  name: puppetserver-dev
items:
  ## DEPLOYMENTCONFIG ##
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: puppetserver-code
        env: dev
      name: puppetserver-code-dev
    spec:
      selector:
        app: puppetserver-code-dev
        deploymentconfig: puppetserver-code-dev
      template:
        metadata:
          labels:
            app: puppetserver-code-dev
            deploymentconfig: puppetserver-code-dev
            env: dev
        spec:
          containers:
            - imagePullPolicy: Always
              image: 'puppetserver-code:dev'
              name: puppetserver-code-dev
              ports:
                - containerPort: 8140
                  protocol: TCP
              volumeMounts:
                - mountPath: /certs
                  name: cert-volume
                  readOnly: true
              readinessProbe:
                failureThreshold: 3
                exec:
                  command:
                    - 'curl -vkl https://localhost:8140/status/v1/services'
                periodSeconds: 10
                timeoutSeconds: 5
                initialDelaySeconds: 120
              livenessProbe:
                tcpSocket:
                  port: 8140
                failureThreshold: 3
                periodSeconds: 10
                timeoutSeconds: 5
                initialDelaySeconds: 30
          volumes:
            - name: cert-volume
              secret:
                defaultMode: 420
                secretName: puppetmaster-certificates
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - puppetserver-code-dev
            from:
              kind: ImageStreamTag
              name: 'puppetserver-code:latest'
          type: ImageChange
  ## SERVICE ##
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: puppetserver-code-dev
      name: puppetserver-code-dev
    spec:
      ports:
        - name: 443-tcp
          port: 443
          protocol: TCP
          targetPort: 8140
      selector:
        deploymentconfig: puppetserver-code-dev
  ## ROUTE ##
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: puppetserver-code-dev
      name: puppetserver-code-dev
    spec:
      host: dev.openshift-puppetmaster.cegeka.be
      port:
        targetPort: 443-tcp
      tls:
        termination: passthrough
      to:
        kind: Service
        name: puppetserver-code-dev

