apiVersion: v1
kind: List
metadata:
  name: puppetserver
items:
## IMAGESTREAM ##
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserver-docker-image
      name: rhel7
    spec:
      tags:
        - from:
            kind: DockerImage
            name: 'registry.redhat.io/rhel7:latest'
          generation: 2
          importPolicy: {}
          name: latest
          referencePolicy:
            type: Source
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserver-docker-image
      name: puppetserver
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserver-code
      name: puppetserver-code
## BUILDCONFIG ##
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: build-puppetserver-docker-image
      name: build-puppetserver-docker-image
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'puppetserver:latest'
      source:
        git:
          ref: s2i
          uri: 'https://github.com/cegeka/docker-puppetserver.git'
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: 'rhel7:latest'
        type: Docker
## BUILDCONFIG code ##
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: build-puppetserver-code
      name: build-puppetserver-code
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'puppetserver-code:latest'
      source:
        git:
          uri: 'git@github.com:cegeka/puppet-monorepo.git'
          ref: 'puppet5'
        sourceSecret:
          name: github-deploykey
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'puppetserver:latest'
        type: Source
      triggers:
        - imageChange:
          type: ImageChange
## DEPLOYMENTCONFIG ##
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: puppetserver-code
      name: puppetserver-code
    spec:
      replicas: 1
      selector:
        app: puppetserver-code
        deploymentconfig: puppetserver-code
      template:
        metadata:
          labels:
            app: puppetserver-code
            deploymentconfig: puppetserver-code
        spec:
          containers:
            - imagePullPolicy: Always
              image: 'puppetserver-code:latest'
              name: puppetserver-code
              ports:
                - containerPort: 8140
                  protocol: TCP
              volumeMounts:
                - mountPath: /certs
                  name: cert-volume
                  readOnly: true
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /status/v1/services
                  port: 8140
                  scheme: HTTPS
                periodSeconds: 10
                timeoutSeconds: 5
                initialDelaySeconds: 120
              livenessProbe:
                tcpSocket:
                  port: 8140
                failureThreshold: 3
                periodSeconds: 10
                timeoutSeconds: 5
                initialDelaySeconds: 30
          volumes:
            - name: cert-volume
              secret:
                defaultMode: 420
                secretName: puppetmaster-certificates
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - puppetserver-code
            from:
              kind: ImageStreamTag
              name: 'puppetserver-code:latest'
          type: ImageChange

## SERVICE ##
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: puppetserver-code
      name: puppetserver-code
    spec:
      ports:
        - name: 443-tcp
          port: 443
          protocol: TCP
          targetPort: 8140
      selector:
        deploymentconfig: puppetserver-code
## ROUTE ##
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: puppetserver-code
      name: puppetserver-code
    spec:
      host: openshift-puppetmaster.cegeka.be
      port:
        targetPort: 443-tcp
      tls:
        termination: passthrough
      to:
        kind: Service
        name: puppetserver-code
