apiVersion: v1
kind: List
metadata:
  name: puppetserver
items:
  ## IMAGESTREAM ##
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserver-docker-image
      name: rhel7
    spec:
      tags:
        - from:
            kind: DockerImage
            name: 'registry.access.redhat.com/rhel7'
          generation: 2
          importPolicy: {}
          name: latest
          referencePolicy:
            type: Source
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserver-docker-image
      name: puppetserver
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserver-code
      name: puppetserver-code
  ## BUILDCONFIG ##
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: build-puppetserver-docker-image
      name: build-puppetserver-docker-image
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'puppetserver:latest'
      source:
        git:
          ref: s2i
          uri: 'https://github.com/cegeka/docker-puppetserver.git'
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: 'rhel7:latest'
        type: Docker
  ## BUILDCONFIG code ##
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: build-puppetserver-code
      name: build-puppetserver-code
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'puppetserver-code:latest'
      source:
        git:
          uri: 'git@github.com:cegeka/puppet-monorepo.git'
          ref: 'puppet5'
        sourceSecret:
          name: github-deploykey
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'puppetserver:latest'
        type: Source
