apiVersion: v1
kind: List
metadata:
  name: puppetserver
items:
## IMAGESTREAM ##
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: build-puppetserver-docker-image
      name: rhel7
    spec:
      tags:
        - from:
            kind: DockerImage
            name: 'registry.redhat.io/rhel7:latest'
          generation: 2
          importPolicy: {}
          name: latest
          referencePolicy:
            type: Source

## BUILDCONFIG ##
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: build-puppetserver-docker-image
      name: build-puppetserver-docker-image
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'puppetserver:latest'
      source:
        git:
          ref: s2i
          uri: 'https://github.com/cegeka/docker-puppetserver.git'
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: 'rhel7:latest'
        type: Docker
## DEPLOYMENTCONFIG ##
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: puppetserver
      name: puppetserver
    spec:
      replicas: 1
      selector:
        app: puppetserver
        deploymentconfig: puppetserver
      template:
        metadata:
          labels:
            app: puppetserver
            deploymentconfig: puppetserver
        spec:
          containers:
            - imagePullPolicy: Always
              name: puppetserver
              ports:
                - containerPort: 8140
                  protocol: TCP
              volumeMounts:
                - mountPath: /certs
                  name: cert-volume
                  readOnly: true
          volumes:
            - name: cert-volume
              secret:
                defaultMode: 420
                secretName: puppetmaster-certificates
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - puppetserver
            from:
              kind: ImageStreamTag
              name: 'puppetserver:latest'
          type: ImageChange
## SERVICE ##
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: puppetserver
      name: puppetserver
    spec:
      ports:
        - name: 443-tcp
          port: 443
          protocol: TCP
          targetPort: 8140
      selector:
        deploymentconfig: puppetserver
## ROUTE ##
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: puppetserver
      name: puppetserver
    spec:
      port:
        targetPort: 443-tcp
      tls:
        termination: passthrough
      to:
        kind: Service
        name: puppetserver
