---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thycotic-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foreman-facts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
