---
apiVersion: v1
data:
  ssh-privatekey: {{ .Values.github_deploy_key | b64enc }}
kind: Secret
metadata:
  name: github-deploy-key
type: kubernetes.io/ssh-auth

---
apiVersion: v1
data:
  puppetmaster.cegeka.be.crt: {{ .Values.puppetmaster_crt | b64enc }}
  puppetmaster.cegeka.be.key: {{ .Values.puppetmaster_key | b64enc }}
  puppetmaster.cegeka.be.ca_crt: {{ .Values.puppetmaster_ca_crt | b64enc }}
kind: Secret
metadata:
  name: certificates
type: Opaque

---
apiVersion: v1
data:
  thycotic.conf: {{ tpl ($.Files.Get "files/puppet/thycotic.conf") $ | b64enc | indent 4 }}
kind: Secret
metadata:
  name: thycotic.conf
type: Opaque


---
apiVersion: v1
data:
  autosigning-credentials.yaml: {{ tpl ($.Files.Get "files/puppet/autosigning-credentials.yaml") $ | b64enc | indent 4 }}
kind: Secret
metadata:
  name: autosigning-credentials.yaml
type: Opaque
