# Update for your Foreman and Puppet master hostname(s)
:url: "AABBCC"  
:ssl_cert: "/certs/AABBCC.crt"
:ssl_key: "/certs/AABBCC.key"

# Advanced settings
:user: "AABBCC"
:password: "AABBCC"
:puppetdir: "/opt/puppetlabs/server/data/puppetserver"
:puppetuser: "puppet"
:facts: true
:timeout: 10
:threads: null
