# Update for your Foreman and Puppet master hostname(s)
:url: "https://foreman.domain.tld"
:ssl_verify: false
:ssl_ca: "/certs/foreman-chain"
:ssl_cert: "/certs/foreman-cert"
:ssl_key: "/certs/foreman-cert-key"

# Advanced settings
:user: "AABBCC"
:password: "AABBCC"
:puppetdir: "/opt/puppetlabs/server/data/puppetserver"
:puppetuser: "puppet"
:facts: true
:timeout: 30
:threads: null
