---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: puppet-jenkins
  name: puppet-jenkins
spec:
  replicas: 1
  selector:
    name: puppet-jenkins
  template:
    metadata:
      labels:
        name: puppet-jenkins
    spec:
      containers:
        - env:
            - name: OPENSHIFT_ENABLE_OAUTH
              value: "true"
            - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
              value: "true"
            - name: DISABLE_ADMINISTRATIVE_MONITORS
              value: "false"
            - name: KUBERNETES_MASTER
              value: https://kubernetes.default:443
            - name: KUBERNETES_TRUST_CERTIFICATES
              value: "true"
            - name: JENKINS_SERVICE_NAME
              value: jenkins
            - name: JNLP_SERVICE_NAME
              value: jenkins-jnlp
            - name: ENABLE_FATAL_ERROR_LOG_FILE
              value: "false"
            - name: INSTALL_PLUGINS
              value: >-
                {{ .Values.jenkins_plugins }}
            - name: CASC_JENKINS_CONFIG
              value: /var/lib/jenkins/init.groovy.d/casc_jenkins.yaml
            - name: PATH
              value: >-
                /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rh/rh-ruby25/root/usr/bin:/opt/rh/rh-ruby25/root/usr/local/bin
            - name: LD_LIBRARY_PATH
              value: /opt/rh/rh-ruby25/root/usr/lib64
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 420
            periodSeconds: 360
            successThreshold: 1
            timeoutSeconds: 240
          name: puppet-jenkins
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 240
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 1Gi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/jenkins
              name: jenkins-volume
            - mountPath: /var/lib/jenkins/.config
              name: yamllint-config
            - mountPath: /var/lib/jenkins/init.groovy.d/
              name: jenkins-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 30
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName: jenkins
        - configMap:
            defaultMode: 420
            items:
              - key: casc.yaml
                path: casc_jenkins.yaml
              - key: config.groovy
                path: config.groovy
            name: {{.Chart.Name}}-jenkins-config
          name: jenkins-config
        - configMap:
            defaultMode: 420
            items:
              - key: yamllint.conf
                path: yamllint
            name: {{.Chart.Name}}-jenkins-config
          name: yamllint-config
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - puppet-jenkins
        from:
          kind: ImageStreamTag
          name: puppet-jenkins:latest
          namespace: {{.Release.Namespace}}
      type: ImageChange
    - type: ConfigChange
