apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: puppet-jenkins
  name: puppetserver-jenkins-test.apps.openshift.cegeka.com
spec:
  host: puppetserver-jenkins-test.apps.openshift.cegeka.com
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jenkins
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-07-01T10:12:35Z'
          status: 'True'
          type: Admitted

